version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "celery -A task.celery_app worker -l info"
    restart: always
    env_file:
      - .env
    volumes:
      - ./src:/app
    # depends_on:
    #   - rabbitmq
    networks:
      - proxynet
networks:
  proxynet:
    name: cb_network
